### ISSUE TITLE
How it is different ?

### ISSUE THREAD

**Issue by famcio** [johnkeymer/apex-google-org-charts-plugin#1]
Thanks John,
Could you tell how it is different than Roel Hartman's?
http://apex-plugin.com/oracle-apex-plugins/region-plugin/google-visualizations-orgchart_187.html ?

Are there any plans to upgrade to this one
https://github.com/dabeng/OrgChart?

**Comment by johnkeymer** [comment]
I wasn't aware that Roel's existed, I had checked on apex.world and there didn't seem to be anything existing, however I should have checked apex-plugin.com as well sorry.
