### ISSUE TITLE
Help/Backend

### ISSUE THREAD

**Issue by Ollwaine** [johnkeymer/apex-google-org-charts-plugin#2]
Hi I need your help 
I’m new to APEX 5.1, and I’ve got the task to create an Orgchart

Because I have no idea how to create one, I’ll was looking for plugins, and I found yours
I’ve imported your plugin in to my application, but I’ve no idea how the select must look like, that it will work

The only table I should use looks like this

T_PERSON
ID_PERSON NUMBER PK
NAME VARCHAR2
ID_PARENT NUMBER FK (id_person)

On your demo-page is only a login to the frontend
Is there a way, that I can take a look in the backend, that I can see how to use our plugin?

**Comment by johnkeymer** [comment]
Hi,
Sorry, I have only just seen this. Did you manage to resolve the problem?

**Comment by johnkeymer** [comment]
Closing due to no response. The help describes the SQL statement requirements.

> Render an organization style chart using the Google Charts API. Accepts a SQL statement as the region source with the following mandatory columns.
> 1) Link - A URL to link the node to. Use Null for none. Ensure you prepare the URL if session state protection is enabled.
> 2) Child Key - The key to use for this node. This can be numeric or text.
> 3) Child Display Value - The text to display. You may use HTML if you have chosen this option.
> 4) Parent Key - The key of this nodes parent.
