### ISSUE TITLE
Not compatible with APEX 5.0

### ISSUE THREAD

**Issue by jeffreykemp** [johnkeymer/apex-google-org-charts-plugin#3]
The plugin appears to have been generated from an APEX 5.1.2 environment so is not allowed to be imported into an APEX 5.0 environment.

**Comment by johnkeymer** [comment]
Oooppps.... Let me see if I can get hold of a 5.0 environment.

**Comment by jeffreykemp** [comment]
I've reverse engineered the code and exported from an APEX 5.0.4 instance:

[region_type_plugin_keymer_john_google_org_chart_apex504.zip](https://github.com/johnkeymer/apex-google-org-charts-plugin/files/2272511/region_type_plugin_keymer_john_google_org_chart_apex504.zip)

**Comment by johnkeymer** [comment]
Thank you, I've committed to the master.

John
